### ISSUE TITLE
Please state intentions and progress

### ISSUE THREAD

**Issue by com2** [microweber-modules/multilanguage#1]
This module is available in the MicroWeber's Marketplace. I hoped it would provide multilingual content with the possibility to translate content pages, products, urls, website name, description and keywords. After installation it did not became clearer what the purpose would be of this module. The readme does not reveal intentions. Would be nice to know what the goals are of this module and what is still missing.

**Comment by peter-mw** [comment]
Hello @com2 , 

if you wish to test this module you will need to pull from the dev branch https://github.com/microweber/microweber/tree/dev  and install module from the marketplace

**Comment by bobimicroweber** [comment]
Hello @com2 

The module is in beta and you can test it on a dev branch.
We work on documentation for multilanguage and we will upload it.
Thank you.

**Comment by bobimicroweber** [comment]
It's officially published, you can download the latest 1.9 version.
