### ISSUE TITLE
Now working with 1click-droplet of Digital ocean

### ISSUE THREAD

**Issue by giorgosn** [microweber-modules/multilanguage#2]
I am working to do multilanguage and does not work.

![image](https://user-images.githubusercontent.com/13453884/78461738-4d491180-76d4-11ea-8f27-effaff3f2d7c.png)

![image](https://user-images.githubusercontent.com/13453884/78461750-5afe9700-76d4-11ea-9778-3a7156309c59.png)

**Comment by bobimicroweber** [comment]
Hello, giorgosn!
The multilanguage is updated you can download the leatest 1.9 version.

**Comment by giorgosn** [comment]
I would be good to update the digital ocean droplet
