### ISSUE TITLE
Option to NOT change admin UI language whilst editing content [FEATURE]

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber-modules/multilanguage#5]
Using MW 1.2 I've installed this Multilanguage module and have enabled Arabic and Russian languages in addition to English. I would like to add text content for the additional 2 languages. Following the animated gif in the readme notes  I changed the language selector in the top menu in live edit, however this also changes the language of the admin menus. I can see that will work fine if admin speaks all relevant languages, however what if admin only speaks English and wishes to add translations obtained from a translator? 

Could an option be added to set/fix the language of the admin controls independant to the language setting for the website please? Maybe admin language could be fixed according to the language selected on the login screen?

How does the auto-detect work? I tried changing my browser language to Russian in Brave browser but it didn't change the page urls.

**Comment by bobimicroweber** [comment]
Hello, we work on upgrading the multilanguage module. You can check it the microweber dev branch and multilanguage master branch to see what is changed. We fix the locales on multilanguage, and _e funciton translation.
For now if you want to translate the content of your website must be switching the different languages in admin top bar.
In future we will think about to add the different languages fields with icon on posts titles and contents.

**Comment by Ezyweb-uk** [comment]
I've retested and it works nicely in admin, content for other languages can now be updated whilst the language of admin menus stays fixed. Thank you for the updates.

It would be great if the website detected the user's locale or browser language and redirected to that language url. 
Reference: 
https://www.geeksforgeeks.org/how-to-detect-browser-language-in-php
https://gist.github.com/LucaRosaldi/5676962
