### ISSUE TITLE
Undefined variable: def_language

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber-modules/multilanguage#6]
In MW 1.2.0: Languages are set in the multilanguage module, then navigate to Website > Settings > Language gives the following error:

ErrorException Undefined variable: def_language 
/admin/view:content/action:settings?group=language

\userfiles\modules\settings\group\language.php:81

**Comment by bobimicroweber** [comment]
We will release the multilanguage and microweber soon. This issue is fixed.
